language: c
dist: xenial
arch: ppc64le
cache: ccache
services:
  - docker
#addon:
#  apt:
#    - quota
env:
  global:
    - ARCH=powerpc
    - IMAGE=ubuntu-19.10
      
script:
  - arch
  - df -H
  - cat /etc/fstab
  - df -i
  - ./file-creator.sh
  
install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)
