#language: c
dist: xenial
arch: ppc64le
#cache: ccache
#services:
#  - docker

#env:
#  global:
#    - ARCH=powerpc
#    - IMAGE=ubuntu-19.10
    
#install:
#  - docker pull linuxppc/build:$IMAGE-$(uname -m)
  
script:
  - arch
  - df -H
