language: c
dist: xenial
arch: ppc64le
jobs:
  include:
    - env: JOB=1
    - env: JOB=2
    - env: JOB=3
    - env: JOB=4
    - env: JOB=5
    - env: JOB=6
    - env: JOB=7
    - env: JOB=8
script:
  - travis_wait 60 sleep 60m &
  - arch
  - df -H
  - df -i
  - cat /dev/urandom | head -c 19GB >> foo.bar
  - df -H
  - df -i
  - sleep 60m
  
